security:
    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider configuration
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        # Secured area with custom authenticators
        secured_area:
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\GoogleAuthenticator  # This line handles the OAuth authenticator
            logout:
                path: app_logout
                
                target: home
                invalidate_session: true

        # Disable security for dev assets

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall for standard form login
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: LogInPage
                check_path: LogInPage
                default_target_path: home
                enable_csrf: true

    access_control:
        # - { path: ^/dashboard, roles: ROLE_ADMIN }
        # - { path: ^/MyAccount, roles: [ROLE_ADMIN, ROLE_CUSTOMER] }
        # - { path: ^/home, roles: ROLE_CUSTOMER }
        # - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }



# Security settings for the test environment
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

services:
    App\Security\OAuthRegistrationService: ~
