services:
    App\Twig\Extension\Base64Extension:
        tags: ['twig.extension']

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

# config/services.yaml
parameters:
    user_id: '%env(USER_ID)%'
    mailer_sender_address: '%env(resolve:MAILER_DSN)%'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    
